# Site settings
# in the templates available like {{ site.myvariable }}.
title: My Portfolio and About me.
email: your-email@domain.com
brand: Burhanudeen
headline: Student for Life, Programmer and Human
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: /portfolio # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2017 Mohd Burhan. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: bern2727@gmail.com
phone: +6-017-376-5314

# Tracking
googleAnalitycsID: UA-83933844-1

